config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :contacts
  root to: "blogs#index"
  resources :favorites, only: [:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :blogs
    has_many :favorites, dependent: :destroy
    validates :name, presence: true
    validates :email, presence: true, 
              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
              validates :email, uniqueness: true
              before_validation { email.downcase! }
              has_secure_password
              validates :password, presence: true, length: { minimum:  6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :ensure_correct_blog, {only: [:edit, :update, :destroy]}
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        #ContactMailer.contact_mail(@blog).deliver 
        redirect_to blogs_path, notice: "ブログを作成しました！"
      else
        render :new
      end
    end
  end
  def show
    #@blog = Blog.find(params[:id])   # 重複！
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  def edit
    @blog = Blog.find(params[:id])   # 重複！
  end
  def update
    @blog = Blog.find(params[:id])   # 重複！
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  
  private

  def ensure_correct_blog
    @blog = Blog.find(params[:id])
    if current_user.id != @blog.user.id
      flash[:notice] = "権限がありません"
      redirect_to blogs_path
    end
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver  ##追記
      redirect_to contacts_path, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
      favorite = current_user.favorites.create(blog_id: params[:blog_id])
      redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
    end
    def destroy
      favorite = current_user.favorites.find_by(id: params[:id]).destroy
      redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
    end
    
    def index
      @favorites = current_user.favorites
    end
    
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       redirect_to user_path(user.id)
    else
       flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end  
  end  

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, {only: [:show, :edit, :update]}

   def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)  
      if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user.id)
      else
          render :new
      end
    end

  def show
    @user = User.find(params[:id])
  end

  def edit
    #@user = User.new(user_params)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path, notice: "ユーザー情報を修正しました"
    else
        render :edit
    end
  end


  private
  def ensure_correct_user
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:notice] = "権限がありません"
      redirect_to blogs_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :image,
                                   :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user 
    @current_user ||= User.find_by(id: session[:user_id])
  end  
    
  def logged_in?
      current_user.present?
  end    
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="blog_title">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>

        
    <div class="field">
       <%= form.label :image %>
       <%= form.file_field :image %><br>
       <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %> 
     </div>

    
    <%= form.submit %>
      <% end %>
    <%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "登録する" %>
<% end %>  

<%= form_with(model:@blog, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを作成する</h2>
  <%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>画像</th>
    <th>投稿者</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= image_tag blog.image.url if blog.image.url %></td>
    <td><%= blog.user.name %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <% if blog.user_id == current_user.id %>
    <td><%= link_to "ブログを編集する", edit_blog_path(blog.id) %></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
  <%= render 'form' %>

app/views/blogs/show.html.erb
# <h1>ブログ詳細画面</h1>
# <p>タイトル: <%= @blog.title %></p>
# <p>内容: <%= @blog.content %></p>
# <p id="notice"><%= notice %></p>

# <p>
#   <strong>Image:</strong>
#   <%= image_tag @blog.image.url %>
# </p>

# <%= link_to 'Edit', edit_blog_path(@blog) %> |
# <%= link_to 'Back', blogs_path %>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>画像</th>
    <th>投稿者</th>
  </tr>
<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.blog.title %></td>
    <td><%= favorite.blog.content %></td>
    <td><%= image_tag favorite.blog.image.url if favorite.blog.image.url %></td>
    <td><%= favorite.blog.user.name %></td>
    <td><%= link_to '詳細を確認する', blog_path(favorite.blog.id) %></td>

  </tr>
<% end %>

</table>
  <%= link_to "ユーザーページに戻る", user_path(current_user.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tukareta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <h1>instance gram</h1>
    </header>

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id) %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Login", new_session_path %>
  <% end %>
    <%= yield %>

    <footer>
     <p>運営会社DIVE INTO CODE株式会社</p>
     <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>編集画面</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div>
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.label :image %>
  <%= f.file_field :image %><br>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %> 
  <span class="btn btn-primary">
  <%= f.submit "更新する" %>
  </span>

   

    
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div>
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.label :image %>
  <%= f.file_field :image %><br>
  %= image_tag(@user.image.url) if @user.image && @user.image.url %> 
  <span class="btn btn-primary">
  <%= f.submit "Create my account" %>
  </span>

   

    
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<td><%= image_tag @user.image.url if @user.image? %></td><br>
<%= link_to "お気に入り一覧だよ", favorites_path %><br>
<%= link_to "ブログ一覧画面", blogs_path %><br>
<%= link_to "プロフィール編集", edit_user_path %><br>
<%= link_to '新しくブログを投稿する', new_blog_path %>